// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CaixaMagica.MunichRE.Data.Models
{
    public partial class Quotes
    {
        public long Id { get; set; }
        public string Quote { get; set; }
        public string Author { get; set; }
    }
}